# Generated by Django 3.2.7 on 2021-09-26 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('host', models.CharField(max_length=255, verbose_name='host')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'allow'), (1, 'block')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('slug', models.CharField(max_length=6, verbose_name='slug')),
                ('url', models.TextField(verbose_name='url')),
                ('visitor_limit', models.IntegerField(null=True, verbose_name='visitor_limit')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='password')),
                ('expire_time', models.DateTimeField(null=True, verbose_name='expire_time')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='link.domain', verbose_name='link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'link',
            },
        ),
    ]
